version: 1.0
app:
  instances:
    min: 1
    max: 2
  version: 5645fc45-f209-4885-ab4d-c4accef66c2c
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
  #mounts:
  #  - path: /opt/ol/wlp/usr/servers/defaultServer/configDropins/overrides/myconfig.xml
  #    value: |
  #      <server>
  #         <var name="io_openliberty_sample_system_inMaintenance" value="false"/>
  #      </server>
